// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ProgramStatus.
const (
	ProgramStatusActive    ProgramStatus = "active"
	ProgramStatusCompleted ProgramStatus = "completed"
	ProgramStatusPlanned   ProgramStatus = "planned"
)

// Defines values for ListProgramsParamsStatus.
const (
	ListProgramsParamsStatusActive    ListProgramsParamsStatus = "active"
	ListProgramsParamsStatusCompleted ListProgramsParamsStatus = "completed"
	ListProgramsParamsStatusPlanned   ListProgramsParamsStatus = "planned"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// GenerateProgramRequest defines model for GenerateProgramRequest.
type GenerateProgramRequest struct {
	// LoadIncrements Map of exercise_name to weight increment in kg for rounding.
	// If not specified, weights are rounded to 0.1 kg precision.
	LoadIncrements *map[string]float64 `json:"load_increments,omitempty"`

	// Name Name for the generated program (defaults to template name)
	Name *string `json:"name,omitempty"`

	// TargetWeights Map of exercise_name to target weight in kg.
	// For entries with percent_1rm: load_kg = percent_1rm * target_weight.
	// For entries without percent_1rm: load_kg = target_weight (direct copy).
	TargetWeights map[string]float64 `json:"target_weights"`
}

// Log defines model for Log.
type Log struct {
	CreatedAt time.Time `json:"created_at"`

	// Entries Performed entries (ordered)
	Entries []LogEntry `json:"entries"`

	// FinishedAt When the training session ended (optional)
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata (e.g., body_weight_kg, fatigue_level)
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Notes General session notes
	Notes *string `json:"notes,omitempty"`

	// PerformedAt When the training was performed
	PerformedAt time.Time `json:"performed_at"`

	// ProgramId Optional reference to the training program
	ProgramId *openapi_types.UUID `json:"program_id"`

	// SessionName Session name (used together with program_id)
	SessionName *string `json:"session_name,omitempty"`

	// StartedAt When the training session started (optional)
	StartedAt *time.Time `json:"started_at,omitempty"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// LogCreate defines model for LogCreate.
type LogCreate struct {
	Entries     []LogEntryCreate        `json:"entries"`
	FinishedAt  *time.Time              `json:"finished_at,omitempty"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Notes       *string                 `json:"notes,omitempty"`
	PerformedAt time.Time               `json:"performed_at"`

	// ProgramId Optional reference to a training program
	ProgramId *openapi_types.UUID `json:"program_id,omitempty"`

	// SessionName Session name (used together with program_id)
	SessionName *string    `json:"session_name,omitempty"`
	StartedAt   *time.Time `json:"started_at,omitempty"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// ExerciseName Exercise name (plain string)
	ExerciseName string `json:"exercise_name"`

	// FinishedAt When the exercise ended (optional)
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// LoadKg Weight in kilograms (0.1 precision)
	LoadKg *float64           `json:"load_kg,omitempty"`
	LogId  openapi_types.UUID `json:"log_id"`

	// Metadata Free-form JSON metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Notes    *string                 `json:"notes,omitempty"`

	// Order Position in log
	Order int  `json:"order"`
	Reps  *int `json:"reps,omitempty"`

	// Rpe Rate of Perceived Exertion
	Rpe  *int `json:"rpe,omitempty"`
	Sets *int `json:"sets,omitempty"`

	// StartedAt When the exercise started (optional)
	StartedAt *time.Time `json:"started_at,omitempty"`

	// VideoObjectKey Object key for uploaded video in storage (from upload-url response)
	VideoObjectKey *string `json:"video_object_key,omitempty"`
}

// LogEntryCreate defines model for LogEntryCreate.
type LogEntryCreate struct {
	ExerciseName   string                  `json:"exercise_name"`
	FinishedAt     *time.Time              `json:"finished_at,omitempty"`
	LoadKg         *float64                `json:"load_kg,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	Notes          *string                 `json:"notes,omitempty"`
	Reps           *int                    `json:"reps,omitempty"`
	Rpe            *int                    `json:"rpe,omitempty"`
	Sets           *int                    `json:"sets,omitempty"`
	StartedAt      *time.Time              `json:"started_at,omitempty"`
	VideoObjectKey *string                 `json:"video_object_key,omitempty"`
}

// LogListResponse defines model for LogListResponse.
type LogListResponse struct {
	Data       []Log   `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// LoggedSessionsResponse defines model for LoggedSessionsResponse.
type LoggedSessionsResponse struct {
	// Sessions Distinct session names that have at least one log for this program
	Sessions []string `json:"sessions"`
}

// Program defines model for Program.
type Program struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata (e.g., generation parameters)
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
	Notes    *string                 `json:"notes,omitempty"`

	// ProgramTemplateId Reference to the source program template (null for manually created programs)
	ProgramTemplateId *openapi_types.UUID `json:"program_template_id"`

	// Sessions Ordered training sessions (each contains entries with absolute weights)
	Sessions []ProgramSession `json:"sessions"`

	// Status active = in progress, completed = all sessions have been logged, planned = not yet started
	Status    ProgramStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// ProgramStatus active = in progress, completed = all sessions have been logged, planned = not yet started
type ProgramStatus string

// ProgramCreate defines model for ProgramCreate.
type ProgramCreate struct {
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
	Notes    *string                 `json:"notes,omitempty"`

	// ProgramTemplateId Optional reference to source program template
	ProgramTemplateId *openapi_types.UUID    `json:"program_template_id,omitempty"`
	Sessions          []ProgramSessionCreate `json:"sessions"`
}

// ProgramListResponse defines model for ProgramListResponse.
type ProgramListResponse struct {
	Data       []Program `json:"data"`
	HasMore    bool      `json:"has_more"`
	NextCursor *string   `json:"next_cursor"`
}

// ProgramSession defines model for ProgramSession.
type ProgramSession struct {
	// Date Scheduled date for this session (YYYY-MM-DD, optional)
	Date *openapi_types.Date `json:"date,omitempty"`

	// Entries Exercise prescriptions with absolute weights
	Entries []ProgramSessionEntry `json:"entries"`
	Id      openapi_types.UUID    `json:"id"`

	// Order Global position in program (0-based)
	Order     int                `json:"order"`
	ProgramId openapi_types.UUID `json:"program_id"`

	// SessionName Day name within the week (e.g., "Day 1", "Heavy", "Volume")
	SessionName string `json:"session_name"`
}

// ProgramSessionCreate defines model for ProgramSessionCreate.
type ProgramSessionCreate struct {
	Date        *openapi_types.Date          `json:"date,omitempty"`
	Entries     *[]ProgramSessionEntryCreate `json:"entries,omitempty"`
	Order       int                          `json:"order"`
	SessionName string                       `json:"session_name"`
}

// ProgramSessionEntry defines model for ProgramSessionEntry.
type ProgramSessionEntry struct {
	// ExerciseName Exercise name (plain string)
	ExerciseName string             `json:"exercise_name"`
	Id           openapi_types.UUID `json:"id"`

	// LoadKg Weight in kilograms (0.1 precision)
	LoadKg *float64 `json:"load_kg,omitempty"`

	// Metadata Free-form JSON metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Notes    *string                 `json:"notes,omitempty"`

	// Order Position in session
	Order int  `json:"order"`
	Reps  *int `json:"reps,omitempty"`

	// Rpe Rate of Perceived Exertion
	Rpe       *int               `json:"rpe,omitempty"`
	SessionId openapi_types.UUID `json:"session_id"`
	Sets      *int               `json:"sets,omitempty"`
}

// ProgramSessionEntryCreate defines model for ProgramSessionEntryCreate.
type ProgramSessionEntryCreate struct {
	ExerciseName string                  `json:"exercise_name"`
	LoadKg       *float64                `json:"load_kg,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Notes        *string                 `json:"notes,omitempty"`
	Order        int                     `json:"order"`
	Reps         *int                    `json:"reps,omitempty"`
	Rpe          *int                    `json:"rpe,omitempty"`
	Sets         *int                    `json:"sets,omitempty"`
}

// ProgramTemplate defines model for ProgramTemplate.
type ProgramTemplate struct {
	// ArchivedAt When set, the program template is archived and hidden from default list results
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`

	// CreatedBy User ID of the creator
	CreatedBy   *string `json:"created_by"`
	Description *string `json:"description,omitempty"`

	// Entries Exercise prescription entries (RPE-based, no absolute weights)
	Entries *[]ProgramTemplateEntry `json:"entries,omitempty"`
	Id      openapi_types.UUID      `json:"id"`

	// Metadata Free-form JSON metadata
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Name      string                  `json:"name"`
	Notes     *string                 `json:"notes,omitempty"`
	UpdatedAt time.Time               `json:"updated_at"`
}

// ProgramTemplateCreate defines model for ProgramTemplateCreate.
type ProgramTemplateCreate struct {
	Description *string                       `json:"description,omitempty"`
	Entries     *[]ProgramTemplateEntryCreate `json:"entries,omitempty"`
	Metadata    *map[string]interface{}       `json:"metadata,omitempty"`
	Name        string                        `json:"name"`
	Notes       *string                       `json:"notes,omitempty"`
}

// ProgramTemplateEntry defines model for ProgramTemplateEntry.
type ProgramTemplateEntry struct {
	// ExerciseName Exercise name (plain string)
	ExerciseName string                  `json:"exercise_name"`
	Id           openapi_types.UUID      `json:"id"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Notes        *string                 `json:"notes,omitempty"`

	// Order Position within the session
	Order int `json:"order"`

	// Percent1rm Percentage of 1RM (0.0 to 1.0) for weight calculation
	Percent1rm        *float64           `json:"percent_1rm,omitempty"`
	ProgramTemplateId openapi_types.UUID `json:"program_template_id"`
	Reps              *int               `json:"reps,omitempty"`

	// Rpe Target Rate of Perceived Exertion
	Rpe  *int `json:"rpe,omitempty"`
	Sets *int `json:"sets,omitempty"`
}

// ProgramTemplateEntryCreate defines model for ProgramTemplateEntryCreate.
type ProgramTemplateEntryCreate struct {
	ExerciseName string                  `json:"exercise_name"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Notes        *string                 `json:"notes,omitempty"`
	Order        int                     `json:"order"`
	Percent1rm   *float64                `json:"percent_1rm,omitempty"`
	Reps         *int                    `json:"reps,omitempty"`
	Rpe          *int                    `json:"rpe,omitempty"`
	Sets         *int                    `json:"sets,omitempty"`
}

// ProgramTemplateListResponse defines model for ProgramTemplateListResponse.
type ProgramTemplateListResponse struct {
	Data       []ProgramTemplate `json:"data"`
	HasMore    bool              `json:"has_more"`
	NextCursor *string           `json:"next_cursor"`
}

// VideoDownloadURLRequest defines model for VideoDownloadURLRequest.
type VideoDownloadURLRequest struct {
	// ObjectKey Object key from LogEntry.video_object_key
	ObjectKey string `json:"object_key"`
}

// VideoDownloadURLResponse defines model for VideoDownloadURLResponse.
type VideoDownloadURLResponse struct {
	// DownloadUrl Pre-signed URL for downloading the video via HTTP GET
	DownloadUrl string `json:"download_url"`

	// ExpiresIn Seconds until the download URL expires
	ExpiresIn int `json:"expires_in"`
}

// VideoUploadURLRequest defines model for VideoUploadURLRequest.
type VideoUploadURLRequest struct {
	// ContentLength File size in bytes
	ContentLength int64 `json:"content_length"`

	// ContentType MIME type of the video file (must be video/*)
	ContentType string `json:"content_type"`

	// Filename Original filename
	Filename string `json:"filename"`
}

// VideoUploadURLResponse defines model for VideoUploadURLResponse.
type VideoUploadURLResponse struct {
	// ExpiresIn Seconds until the upload URL expires
	ExpiresIn int `json:"expires_in"`

	// ObjectKey Object key to be stored in LogEntry.video_object_key after successful upload
	ObjectKey string `json:"object_key"`

	// UploadUrl Pre-signed URL for uploading the video via HTTP PUT
	UploadUrl string `json:"upload_url"`
}

// After defines model for After.
type After = string

// Limit defines model for Limit.
type Limit = int

// LogId defines model for LogId.
type LogId = openapi_types.UUID

// ProgramId defines model for ProgramId.
type ProgramId = openapi_types.UUID

// ProgramTemplateId defines model for ProgramTemplateId.
type ProgramTemplateId = openapi_types.UUID

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// ListLogsParams defines parameters for ListLogs.
type ListLogsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// ProgramId Filter logs by program ID
	ProgramId *openapi_types.UUID `form:"program_id,omitempty" json:"program_id,omitempty"`

	// PerformedAtFrom Filter logs at or after this timestamp
	PerformedAtFrom *time.Time `form:"performed_at_from,omitempty" json:"performed_at_from,omitempty"`

	// PerformedAtTo Filter logs before this timestamp
	PerformedAtTo *time.Time `form:"performed_at_to,omitempty" json:"performed_at_to,omitempty"`
}

// ListProgramTemplatesParams defines parameters for ListProgramTemplates.
type ListProgramTemplatesParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// IncludeArchived When true, archived program templates are included in results
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// ListProgramsParams defines parameters for ListPrograms.
type ListProgramsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// ProgramTemplateId Filter programs by source program template ID
	ProgramTemplateId *openapi_types.UUID `form:"program_template_id,omitempty" json:"program_template_id,omitempty"`

	// Status Filter programs by status
	Status *ListProgramsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListProgramsParamsStatus defines parameters for ListPrograms.
type ListProgramsParamsStatus string

// CreateLogJSONRequestBody defines body for CreateLog for application/json ContentType.
type CreateLogJSONRequestBody = LogCreate

// UpdateLogJSONRequestBody defines body for UpdateLog for application/json ContentType.
type UpdateLogJSONRequestBody = LogCreate

// CreateProgramTemplateJSONRequestBody defines body for CreateProgramTemplate for application/json ContentType.
type CreateProgramTemplateJSONRequestBody = ProgramTemplateCreate

// GenerateProgramJSONRequestBody defines body for GenerateProgram for application/json ContentType.
type GenerateProgramJSONRequestBody = GenerateProgramRequest

// CreateProgramJSONRequestBody defines body for CreateProgram for application/json ContentType.
type CreateProgramJSONRequestBody = ProgramCreate

// GenerateVideoDownloadURLJSONRequestBody defines body for GenerateVideoDownloadURL for application/json ContentType.
type GenerateVideoDownloadURLJSONRequestBody = VideoDownloadURLRequest

// GenerateVideoUploadURLJSONRequestBody defines body for GenerateVideoUploadURL for application/json ContentType.
type GenerateVideoUploadURLJSONRequestBody = VideoUploadURLRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List logs
	// (GET /logs)
	ListLogs(w http.ResponseWriter, r *http.Request, params ListLogsParams)
	// Create log
	// (POST /logs)
	CreateLog(w http.ResponseWriter, r *http.Request)
	// Delete log
	// (DELETE /logs/{id})
	DeleteLog(w http.ResponseWriter, r *http.Request, id LogId)
	// Get log by ID
	// (GET /logs/{id})
	GetLog(w http.ResponseWriter, r *http.Request, id LogId)
	// Update log
	// (PUT /logs/{id})
	UpdateLog(w http.ResponseWriter, r *http.Request, id LogId)
	// List program templates
	// (GET /program-templates)
	ListProgramTemplates(w http.ResponseWriter, r *http.Request, params ListProgramTemplatesParams)
	// Create program template
	// (POST /program-templates)
	CreateProgramTemplate(w http.ResponseWriter, r *http.Request)
	// Delete program template
	// (DELETE /program-templates/{id})
	DeleteProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId)
	// Get program template by ID
	// (GET /program-templates/{id})
	GetProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId)
	// Archive program template
	// (POST /program-templates/{id}/archive)
	ArchiveProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId)
	// Duplicate program template
	// (POST /program-templates/{id}/duplicate)
	DuplicateProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId)
	// Generate a Program from this template
	// (POST /program-templates/{id}/generate)
	GenerateProgram(w http.ResponseWriter, r *http.Request, id ProgramTemplateId)
	// Unarchive program template
	// (POST /program-templates/{id}/unarchive)
	UnarchiveProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId)
	// List programs
	// (GET /programs)
	ListPrograms(w http.ResponseWriter, r *http.Request, params ListProgramsParams)
	// Create program
	// (POST /programs)
	CreateProgram(w http.ResponseWriter, r *http.Request)
	// Delete program
	// (DELETE /programs/{id})
	DeleteProgram(w http.ResponseWriter, r *http.Request, id ProgramId)
	// Get program by ID
	// (GET /programs/{id})
	GetProgram(w http.ResponseWriter, r *http.Request, id ProgramId)
	// List distinct logged session names for a program
	// (GET /programs/{id}/logged-sessions)
	ListLoggedSessions(w http.ResponseWriter, r *http.Request, id ProgramId)
	// Generate pre-signed URL for video download
	// (POST /videos/download-url)
	GenerateVideoDownloadURL(w http.ResponseWriter, r *http.Request)
	// Generate pre-signed URL for video upload
	// (POST /videos/upload-url)
	GenerateVideoUploadURL(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List logs
// (GET /logs)
func (_ Unimplemented) ListLogs(w http.ResponseWriter, r *http.Request, params ListLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create log
// (POST /logs)
func (_ Unimplemented) CreateLog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete log
// (DELETE /logs/{id})
func (_ Unimplemented) DeleteLog(w http.ResponseWriter, r *http.Request, id LogId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get log by ID
// (GET /logs/{id})
func (_ Unimplemented) GetLog(w http.ResponseWriter, r *http.Request, id LogId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update log
// (PUT /logs/{id})
func (_ Unimplemented) UpdateLog(w http.ResponseWriter, r *http.Request, id LogId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List program templates
// (GET /program-templates)
func (_ Unimplemented) ListProgramTemplates(w http.ResponseWriter, r *http.Request, params ListProgramTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create program template
// (POST /program-templates)
func (_ Unimplemented) CreateProgramTemplate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete program template
// (DELETE /program-templates/{id})
func (_ Unimplemented) DeleteProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get program template by ID
// (GET /program-templates/{id})
func (_ Unimplemented) GetProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Archive program template
// (POST /program-templates/{id}/archive)
func (_ Unimplemented) ArchiveProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Duplicate program template
// (POST /program-templates/{id}/duplicate)
func (_ Unimplemented) DuplicateProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a Program from this template
// (POST /program-templates/{id}/generate)
func (_ Unimplemented) GenerateProgram(w http.ResponseWriter, r *http.Request, id ProgramTemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unarchive program template
// (POST /program-templates/{id}/unarchive)
func (_ Unimplemented) UnarchiveProgramTemplate(w http.ResponseWriter, r *http.Request, id ProgramTemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List programs
// (GET /programs)
func (_ Unimplemented) ListPrograms(w http.ResponseWriter, r *http.Request, params ListProgramsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create program
// (POST /programs)
func (_ Unimplemented) CreateProgram(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete program
// (DELETE /programs/{id})
func (_ Unimplemented) DeleteProgram(w http.ResponseWriter, r *http.Request, id ProgramId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get program by ID
// (GET /programs/{id})
func (_ Unimplemented) GetProgram(w http.ResponseWriter, r *http.Request, id ProgramId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List distinct logged session names for a program
// (GET /programs/{id}/logged-sessions)
func (_ Unimplemented) ListLoggedSessions(w http.ResponseWriter, r *http.Request, id ProgramId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate pre-signed URL for video download
// (POST /videos/download-url)
func (_ Unimplemented) GenerateVideoDownloadURL(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate pre-signed URL for video upload
// (POST /videos/upload-url)
func (_ Unimplemented) GenerateVideoUploadURL(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLogs operation middleware
func (siw *ServerInterfaceWrapper) ListLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "program_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "program_id", r.URL.Query(), &params.ProgramId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "program_id", Err: err})
		return
	}

	// ------------- Optional query parameter "performed_at_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "performed_at_from", r.URL.Query(), &params.PerformedAtFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performed_at_from", Err: err})
		return
	}

	// ------------- Optional query parameter "performed_at_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "performed_at_to", r.URL.Query(), &params.PerformedAtTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performed_at_to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLog operation middleware
func (siw *ServerInterfaceWrapper) CreateLog(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLog operation middleware
func (siw *ServerInterfaceWrapper) DeleteLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id LogId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLog operation middleware
func (siw *ServerInterfaceWrapper) GetLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id LogId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLog operation middleware
func (siw *ServerInterfaceWrapper) UpdateLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id LogId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProgramTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListProgramTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProgramTemplatesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "include_archived" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_archived", r.URL.Query(), &params.IncludeArchived)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProgramTemplates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProgramTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateProgramTemplate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProgramTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProgramTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteProgramTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramTemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProgramTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgramTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetProgramTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramTemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgramTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveProgramTemplate operation middleware
func (siw *ServerInterfaceWrapper) ArchiveProgramTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramTemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveProgramTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DuplicateProgramTemplate operation middleware
func (siw *ServerInterfaceWrapper) DuplicateProgramTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramTemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DuplicateProgramTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateProgram operation middleware
func (siw *ServerInterfaceWrapper) GenerateProgram(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramTemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateProgram(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnarchiveProgramTemplate operation middleware
func (siw *ServerInterfaceWrapper) UnarchiveProgramTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramTemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnarchiveProgramTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPrograms operation middleware
func (siw *ServerInterfaceWrapper) ListPrograms(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProgramsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "program_template_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "program_template_id", r.URL.Query(), &params.ProgramTemplateId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "program_template_id", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPrograms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProgram operation middleware
func (siw *ServerInterfaceWrapper) CreateProgram(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProgram(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProgram operation middleware
func (siw *ServerInterfaceWrapper) DeleteProgram(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProgram(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgram operation middleware
func (siw *ServerInterfaceWrapper) GetProgram(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgram(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLoggedSessions operation middleware
func (siw *ServerInterfaceWrapper) ListLoggedSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLoggedSessions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVideoDownloadURL operation middleware
func (siw *ServerInterfaceWrapper) GenerateVideoDownloadURL(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVideoDownloadURL(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVideoUploadURL operation middleware
func (siw *ServerInterfaceWrapper) GenerateVideoUploadURL(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVideoUploadURL(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs", wrapper.ListLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/logs", wrapper.CreateLog)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/logs/{id}", wrapper.DeleteLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs/{id}", wrapper.GetLog)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/logs/{id}", wrapper.UpdateLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/program-templates", wrapper.ListProgramTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/program-templates", wrapper.CreateProgramTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/program-templates/{id}", wrapper.DeleteProgramTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/program-templates/{id}", wrapper.GetProgramTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/program-templates/{id}/archive", wrapper.ArchiveProgramTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/program-templates/{id}/duplicate", wrapper.DuplicateProgramTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/program-templates/{id}/generate", wrapper.GenerateProgram)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/program-templates/{id}/unarchive", wrapper.UnarchiveProgramTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs", wrapper.ListPrograms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/programs", wrapper.CreateProgram)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/programs/{id}", wrapper.DeleteProgram)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs/{id}", wrapper.GetProgram)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs/{id}/logged-sessions", wrapper.ListLoggedSessions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/download-url", wrapper.GenerateVideoDownloadURL)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/upload-url", wrapper.GenerateVideoUploadURL)
	})

	return r
}
