// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ConvertProgramToPlanRequest defines model for ConvertProgramToPlanRequest.
type ConvertProgramToPlanRequest struct {
	// LoadIncrements Map of exercise_name to weight increment in kg for rounding.
	// If not specified, weights are rounded to 0.1 kg precision.
	LoadIncrements *map[string]float64 `json:"load_increments,omitempty"`

	// Name Name for the created plan (defaults to program name)
	Name *string `json:"name,omitempty"`

	// ProgramId ID of the program to convert
	ProgramId openapi_types.UUID `json:"program_id"`

	// TargetWeights Map of exercise_name to target weight in kg.
	// For entries with percent_1rm: load_kg = percent_1rm * target_weight.
	// For entries without percent_1rm: load_kg = target_weight (direct copy).
	TargetWeights map[string]float64 `json:"target_weights"`
}

// Cycle defines model for Cycle.
type Cycle struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata (e.g., conversion parameters)
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
	Notes    *string                 `json:"notes,omitempty"`

	// ProgramId Reference to the source program
	ProgramId openapi_types.UUID `json:"program_id"`
}

// CycleListResponse defines model for CycleListResponse.
type CycleListResponse struct {
	Data       []Cycle `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Log defines model for Log.
type Log struct {
	CreatedAt time.Time `json:"created_at"`

	// Entries Performed entries (ordered)
	Entries []LogEntry `json:"entries"`

	// FinishedAt When the training session ended (optional)
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata (e.g., body_weight_kg, fatigue_level)
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Notes General session notes
	Notes *string `json:"notes,omitempty"`

	// PerformedAt When the training was performed
	PerformedAt time.Time `json:"performed_at"`

	// PlanId Optional reference to the training plan
	PlanId *openapi_types.UUID `json:"plan_id,omitempty"`

	// StartedAt When the training session started (optional)
	StartedAt *time.Time `json:"started_at,omitempty"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// LogCreate defines model for LogCreate.
type LogCreate struct {
	Entries     []LogEntryCreate        `json:"entries"`
	FinishedAt  *time.Time              `json:"finished_at,omitempty"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Notes       *string                 `json:"notes,omitempty"`
	PerformedAt time.Time               `json:"performed_at"`
	PlanId      *openapi_types.UUID     `json:"plan_id,omitempty"`
	StartedAt   *time.Time              `json:"started_at,omitempty"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// ExerciseName Exercise name (plain string)
	ExerciseName string `json:"exercise_name"`

	// FinishedAt When the exercise ended (optional)
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// LoadKg Weight in kilograms (0.1 precision)
	LoadKg *float64           `json:"load_kg,omitempty"`
	LogId  openapi_types.UUID `json:"log_id"`

	// Metadata Free-form JSON metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Notes    *string                 `json:"notes,omitempty"`

	// Order Position in log
	Order int  `json:"order"`
	Reps  *int `json:"reps,omitempty"`

	// Rpe Rate of Perceived Exertion
	Rpe  *int `json:"rpe,omitempty"`
	Sets *int `json:"sets,omitempty"`

	// StartedAt When the exercise started (optional)
	StartedAt *time.Time `json:"started_at,omitempty"`

	// VideoObjectKey Object key for uploaded video in storage (from upload-url response)
	VideoObjectKey *string `json:"video_object_key,omitempty"`
}

// LogEntryCreate defines model for LogEntryCreate.
type LogEntryCreate struct {
	ExerciseName   string                  `json:"exercise_name"`
	FinishedAt     *time.Time              `json:"finished_at,omitempty"`
	LoadKg         *float64                `json:"load_kg,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	Notes          *string                 `json:"notes,omitempty"`
	Reps           *int                    `json:"reps,omitempty"`
	Rpe            *int                    `json:"rpe,omitempty"`
	Sets           *int                    `json:"sets,omitempty"`
	StartedAt      *time.Time              `json:"started_at,omitempty"`
	VideoObjectKey *string                 `json:"video_object_key,omitempty"`
}

// LogListResponse defines model for LogListResponse.
type LogListResponse struct {
	Data       []Log   `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// Plan defines model for Plan.
type Plan struct {
	CreatedAt time.Time `json:"created_at"`

	// Date Scheduled date for this session (YYYY-MM-DD)
	Date        *openapi_types.Date `json:"date,omitempty"`
	Description *string             `json:"description,omitempty"`

	// Entries Training prescription entries
	Entries *[]PlanEntry       `json:"entries,omitempty"`
	Id      openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
	Notes    *string                 `json:"notes,omitempty"`

	// ProgramId Optional reference to the source program template
	ProgramId *openapi_types.UUID `json:"program_id,omitempty"`

	// SessionName Session name from the source program (e.g. "Day A", "Upper")
	SessionName *string   `json:"session_name,omitempty"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// PlanCreate defines model for PlanCreate.
type PlanCreate struct {
	// Date Scheduled date for this session (YYYY-MM-DD)
	Date        *openapi_types.Date     `json:"date,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Entries     *[]PlanEntryCreate      `json:"entries,omitempty"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Name        string                  `json:"name"`
	Notes       *string                 `json:"notes,omitempty"`
	ProgramId   *openapi_types.UUID     `json:"program_id,omitempty"`

	// SessionName Session name (e.g. "Day A", "Upper")
	SessionName *string `json:"session_name,omitempty"`
}

// PlanEntry defines model for PlanEntry.
type PlanEntry struct {
	// ExerciseName Exercise name (plain string)
	ExerciseName string             `json:"exercise_name"`
	Id           openapi_types.UUID `json:"id"`

	// LoadKg Weight in kilograms (0.1 precision)
	LoadKg *float64 `json:"load_kg,omitempty"`

	// Metadata Free-form JSON metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Notes    *string                 `json:"notes,omitempty"`

	// Order Position in plan
	Order  int                `json:"order"`
	PlanId openapi_types.UUID `json:"plan_id"`
	Reps   *int               `json:"reps,omitempty"`

	// Rpe Rate of Perceived Exertion
	Rpe  *int `json:"rpe,omitempty"`
	Sets *int `json:"sets,omitempty"`
}

// PlanEntryCreate defines model for PlanEntryCreate.
type PlanEntryCreate struct {
	ExerciseName string                  `json:"exercise_name"`
	LoadKg       *float64                `json:"load_kg,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Notes        *string                 `json:"notes,omitempty"`
	Order        int                     `json:"order"`
	Reps         *int                    `json:"reps,omitempty"`
	Rpe          *int                    `json:"rpe,omitempty"`
	Sets         *int                    `json:"sets,omitempty"`
}

// PlanListResponse defines model for PlanListResponse.
type PlanListResponse struct {
	Data       []Plan  `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// Program defines model for Program.
type Program struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`

	// Entries Exercise prescription entries (RPE-based, no absolute weights)
	Entries *[]ProgramEntry    `json:"entries,omitempty"`
	Id      openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Name      string                  `json:"name"`
	Notes     *string                 `json:"notes,omitempty"`
	UpdatedAt time.Time               `json:"updated_at"`
}

// ProgramCreate defines model for ProgramCreate.
type ProgramCreate struct {
	Description *string                 `json:"description,omitempty"`
	Entries     *[]ProgramEntryCreate   `json:"entries,omitempty"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Name        string                  `json:"name"`
	Notes       *string                 `json:"notes,omitempty"`
}

// ProgramEntry defines model for ProgramEntry.
type ProgramEntry struct {
	// ExerciseName Exercise name (plain string)
	ExerciseName string             `json:"exercise_name"`
	Id           openapi_types.UUID `json:"id"`

	// Metadata Free-form JSON metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Notes    *string                 `json:"notes,omitempty"`

	// Order Position in program
	Order int `json:"order"`

	// Percent1rm Percentage of 1RM (0.0 to 1.0) for weight calculation
	Percent1rm *float64           `json:"percent_1rm,omitempty"`
	ProgramId  openapi_types.UUID `json:"program_id"`
	Reps       *int               `json:"reps,omitempty"`

	// Rpe Target Rate of Perceived Exertion
	Rpe  *int `json:"rpe,omitempty"`
	Sets *int `json:"sets,omitempty"`
}

// ProgramEntryCreate defines model for ProgramEntryCreate.
type ProgramEntryCreate struct {
	ExerciseName string                  `json:"exercise_name"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Notes        *string                 `json:"notes,omitempty"`
	Order        int                     `json:"order"`
	Percent1rm   *float64                `json:"percent_1rm,omitempty"`
	Reps         *int                    `json:"reps,omitempty"`
	Rpe          *int                    `json:"rpe,omitempty"`
	Sets         *int                    `json:"sets,omitempty"`
}

// ProgramListResponse defines model for ProgramListResponse.
type ProgramListResponse struct {
	Data       []Program `json:"data"`
	HasMore    bool      `json:"has_more"`
	NextCursor *string   `json:"next_cursor"`
}

// VideoDownloadURLRequest defines model for VideoDownloadURLRequest.
type VideoDownloadURLRequest struct {
	// ObjectKey Object key from LogEntry.video_object_key
	ObjectKey string `json:"object_key"`
}

// VideoDownloadURLResponse defines model for VideoDownloadURLResponse.
type VideoDownloadURLResponse struct {
	// DownloadUrl Pre-signed URL for downloading the video via HTTP GET
	DownloadUrl string `json:"download_url"`

	// ExpiresIn Seconds until the download URL expires
	ExpiresIn int `json:"expires_in"`
}

// VideoUploadURLRequest defines model for VideoUploadURLRequest.
type VideoUploadURLRequest struct {
	// ContentLength File size in bytes
	ContentLength int64 `json:"content_length"`

	// ContentType MIME type of the video file (must be video/*)
	ContentType string `json:"content_type"`

	// Filename Original filename
	Filename string `json:"filename"`
}

// VideoUploadURLResponse defines model for VideoUploadURLResponse.
type VideoUploadURLResponse struct {
	// ExpiresIn Seconds until the upload URL expires
	ExpiresIn int `json:"expires_in"`

	// ObjectKey Object key to be stored in LogEntry.video_object_key after successful upload
	ObjectKey string `json:"object_key"`

	// UploadUrl Pre-signed URL for uploading the video via HTTP PUT
	UploadUrl string `json:"upload_url"`
}

// After defines model for After.
type After = string

// CycleId defines model for CycleId.
type CycleId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// LogId defines model for LogId.
type LogId = openapi_types.UUID

// PlanId defines model for PlanId.
type PlanId = openapi_types.UUID

// ProgramId defines model for ProgramId.
type ProgramId = openapi_types.UUID

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// ListCyclesParams defines parameters for ListCycles.
type ListCyclesParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// ProgramId Filter cycles by program ID
	ProgramId *openapi_types.UUID `form:"program_id,omitempty" json:"program_id,omitempty"`
}

// ListLogsParams defines parameters for ListLogs.
type ListLogsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// PerformedAtFrom Filter logs at or after this timestamp
	PerformedAtFrom *time.Time `form:"performed_at_from,omitempty" json:"performed_at_from,omitempty"`

	// PerformedAtTo Filter logs before this timestamp
	PerformedAtTo *time.Time `form:"performed_at_to,omitempty" json:"performed_at_to,omitempty"`
}

// ListPlansParams defines parameters for ListPlans.
type ListPlansParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// ProgramId Filter plans by source program ID
	ProgramId *openapi_types.UUID `form:"program_id,omitempty" json:"program_id,omitempty"`
}

// ListProgramsParams defines parameters for ListPrograms.
type ListProgramsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// After Cursor for pagination (from previous response)
	After *After `form:"after,omitempty" json:"after,omitempty"`
}

// CreateLogJSONRequestBody defines body for CreateLog for application/json ContentType.
type CreateLogJSONRequestBody = LogCreate

// UpdateLogJSONRequestBody defines body for UpdateLog for application/json ContentType.
type UpdateLogJSONRequestBody = LogCreate

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = PlanCreate

// ConvertProgramToPlansJSONRequestBody defines body for ConvertProgramToPlans for application/json ContentType.
type ConvertProgramToPlansJSONRequestBody = ConvertProgramToPlanRequest

// UpdatePlanJSONRequestBody defines body for UpdatePlan for application/json ContentType.
type UpdatePlanJSONRequestBody = PlanCreate

// CreateProgramJSONRequestBody defines body for CreateProgram for application/json ContentType.
type CreateProgramJSONRequestBody = ProgramCreate

// UpdateProgramJSONRequestBody defines body for UpdateProgram for application/json ContentType.
type UpdateProgramJSONRequestBody = ProgramCreate

// GenerateVideoDownloadURLJSONRequestBody defines body for GenerateVideoDownloadURL for application/json ContentType.
type GenerateVideoDownloadURLJSONRequestBody = VideoDownloadURLRequest

// GenerateVideoUploadURLJSONRequestBody defines body for GenerateVideoUploadURL for application/json ContentType.
type GenerateVideoUploadURLJSONRequestBody = VideoUploadURLRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cycles
	// (GET /cycles)
	ListCycles(w http.ResponseWriter, r *http.Request, params ListCyclesParams)
	// Delete cycle
	// (DELETE /cycles/{id})
	DeleteCycle(w http.ResponseWriter, r *http.Request, id CycleId)
	// Get cycle by ID
	// (GET /cycles/{id})
	GetCycle(w http.ResponseWriter, r *http.Request, id CycleId)
	// List logs
	// (GET /logs)
	ListLogs(w http.ResponseWriter, r *http.Request, params ListLogsParams)
	// Create log
	// (POST /logs)
	CreateLog(w http.ResponseWriter, r *http.Request)
	// Delete log
	// (DELETE /logs/{id})
	DeleteLog(w http.ResponseWriter, r *http.Request, id LogId)
	// Get log by ID
	// (GET /logs/{id})
	GetLog(w http.ResponseWriter, r *http.Request, id LogId)
	// Update log
	// (PUT /logs/{id})
	UpdateLog(w http.ResponseWriter, r *http.Request, id LogId)
	// List plans
	// (GET /plans)
	ListPlans(w http.ResponseWriter, r *http.Request, params ListPlansParams)
	// Create plan
	// (POST /plans)
	CreatePlan(w http.ResponseWriter, r *http.Request)
	// Convert a program into plans (one per session)
	// (POST /plans/from-program)
	ConvertProgramToPlans(w http.ResponseWriter, r *http.Request)
	// Delete plan
	// (DELETE /plans/{id})
	DeletePlan(w http.ResponseWriter, r *http.Request, id PlanId)
	// Get plan by ID
	// (GET /plans/{id})
	GetPlan(w http.ResponseWriter, r *http.Request, id PlanId)
	// Update plan
	// (PUT /plans/{id})
	UpdatePlan(w http.ResponseWriter, r *http.Request, id PlanId)
	// List programs
	// (GET /programs)
	ListPrograms(w http.ResponseWriter, r *http.Request, params ListProgramsParams)
	// Create program
	// (POST /programs)
	CreateProgram(w http.ResponseWriter, r *http.Request)
	// Delete program
	// (DELETE /programs/{id})
	DeleteProgram(w http.ResponseWriter, r *http.Request, id ProgramId)
	// Get program by ID
	// (GET /programs/{id})
	GetProgram(w http.ResponseWriter, r *http.Request, id ProgramId)
	// Update program
	// (PUT /programs/{id})
	UpdateProgram(w http.ResponseWriter, r *http.Request, id ProgramId)
	// Generate pre-signed URL for video download
	// (POST /videos/download-url)
	GenerateVideoDownloadURL(w http.ResponseWriter, r *http.Request)
	// Generate pre-signed URL for video upload
	// (POST /videos/upload-url)
	GenerateVideoUploadURL(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List cycles
// (GET /cycles)
func (_ Unimplemented) ListCycles(w http.ResponseWriter, r *http.Request, params ListCyclesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete cycle
// (DELETE /cycles/{id})
func (_ Unimplemented) DeleteCycle(w http.ResponseWriter, r *http.Request, id CycleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cycle by ID
// (GET /cycles/{id})
func (_ Unimplemented) GetCycle(w http.ResponseWriter, r *http.Request, id CycleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List logs
// (GET /logs)
func (_ Unimplemented) ListLogs(w http.ResponseWriter, r *http.Request, params ListLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create log
// (POST /logs)
func (_ Unimplemented) CreateLog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete log
// (DELETE /logs/{id})
func (_ Unimplemented) DeleteLog(w http.ResponseWriter, r *http.Request, id LogId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get log by ID
// (GET /logs/{id})
func (_ Unimplemented) GetLog(w http.ResponseWriter, r *http.Request, id LogId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update log
// (PUT /logs/{id})
func (_ Unimplemented) UpdateLog(w http.ResponseWriter, r *http.Request, id LogId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List plans
// (GET /plans)
func (_ Unimplemented) ListPlans(w http.ResponseWriter, r *http.Request, params ListPlansParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create plan
// (POST /plans)
func (_ Unimplemented) CreatePlan(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Convert a program into plans (one per session)
// (POST /plans/from-program)
func (_ Unimplemented) ConvertProgramToPlans(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete plan
// (DELETE /plans/{id})
func (_ Unimplemented) DeletePlan(w http.ResponseWriter, r *http.Request, id PlanId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get plan by ID
// (GET /plans/{id})
func (_ Unimplemented) GetPlan(w http.ResponseWriter, r *http.Request, id PlanId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update plan
// (PUT /plans/{id})
func (_ Unimplemented) UpdatePlan(w http.ResponseWriter, r *http.Request, id PlanId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List programs
// (GET /programs)
func (_ Unimplemented) ListPrograms(w http.ResponseWriter, r *http.Request, params ListProgramsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create program
// (POST /programs)
func (_ Unimplemented) CreateProgram(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete program
// (DELETE /programs/{id})
func (_ Unimplemented) DeleteProgram(w http.ResponseWriter, r *http.Request, id ProgramId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get program by ID
// (GET /programs/{id})
func (_ Unimplemented) GetProgram(w http.ResponseWriter, r *http.Request, id ProgramId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update program
// (PUT /programs/{id})
func (_ Unimplemented) UpdateProgram(w http.ResponseWriter, r *http.Request, id ProgramId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate pre-signed URL for video download
// (POST /videos/download-url)
func (_ Unimplemented) GenerateVideoDownloadURL(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate pre-signed URL for video upload
// (POST /videos/upload-url)
func (_ Unimplemented) GenerateVideoUploadURL(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCycles operation middleware
func (siw *ServerInterfaceWrapper) ListCycles(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCyclesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "program_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "program_id", r.URL.Query(), &params.ProgramId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "program_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCycles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCycle operation middleware
func (siw *ServerInterfaceWrapper) DeleteCycle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id CycleId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCycle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCycle operation middleware
func (siw *ServerInterfaceWrapper) GetCycle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id CycleId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCycle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLogs operation middleware
func (siw *ServerInterfaceWrapper) ListLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "performed_at_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "performed_at_from", r.URL.Query(), &params.PerformedAtFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performed_at_from", Err: err})
		return
	}

	// ------------- Optional query parameter "performed_at_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "performed_at_to", r.URL.Query(), &params.PerformedAtTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performed_at_to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLog operation middleware
func (siw *ServerInterfaceWrapper) CreateLog(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLog operation middleware
func (siw *ServerInterfaceWrapper) DeleteLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id LogId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLog operation middleware
func (siw *ServerInterfaceWrapper) GetLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id LogId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLog operation middleware
func (siw *ServerInterfaceWrapper) UpdateLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id LogId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlans operation middleware
func (siw *ServerInterfaceWrapper) ListPlans(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlansParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "program_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "program_id", r.URL.Query(), &params.ProgramId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "program_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlans(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlan operation middleware
func (siw *ServerInterfaceWrapper) CreatePlan(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConvertProgramToPlans operation middleware
func (siw *ServerInterfaceWrapper) ConvertProgramToPlans(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConvertProgramToPlans(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlan operation middleware
func (siw *ServerInterfaceWrapper) DeletePlan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PlanId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlan(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlan operation middleware
func (siw *ServerInterfaceWrapper) GetPlan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PlanId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlan(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlan operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PlanId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlan(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPrograms operation middleware
func (siw *ServerInterfaceWrapper) ListPrograms(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProgramsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPrograms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProgram operation middleware
func (siw *ServerInterfaceWrapper) CreateProgram(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProgram(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProgram operation middleware
func (siw *ServerInterfaceWrapper) DeleteProgram(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProgram(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgram operation middleware
func (siw *ServerInterfaceWrapper) GetProgram(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgram(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProgram operation middleware
func (siw *ServerInterfaceWrapper) UpdateProgram(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProgramId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProgram(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVideoDownloadURL operation middleware
func (siw *ServerInterfaceWrapper) GenerateVideoDownloadURL(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVideoDownloadURL(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVideoUploadURL operation middleware
func (siw *ServerInterfaceWrapper) GenerateVideoUploadURL(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVideoUploadURL(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cycles", wrapper.ListCycles)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cycles/{id}", wrapper.DeleteCycle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cycles/{id}", wrapper.GetCycle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs", wrapper.ListLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/logs", wrapper.CreateLog)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/logs/{id}", wrapper.DeleteLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs/{id}", wrapper.GetLog)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/logs/{id}", wrapper.UpdateLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/plans", wrapper.ListPlans)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/plans", wrapper.CreatePlan)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/plans/from-program", wrapper.ConvertProgramToPlans)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/plans/{id}", wrapper.DeletePlan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/plans/{id}", wrapper.GetPlan)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/plans/{id}", wrapper.UpdatePlan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs", wrapper.ListPrograms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/programs", wrapper.CreateProgram)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/programs/{id}", wrapper.DeleteProgram)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs/{id}", wrapper.GetProgram)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/programs/{id}", wrapper.UpdateProgram)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/download-url", wrapper.GenerateVideoDownloadURL)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/upload-url", wrapper.GenerateVideoUploadURL)
	})

	return r
}
