DROP TABLE IF EXISTS log_entries CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS program_session_entries CASCADE;
DROP TABLE IF EXISTS program_sessions CASCADE;
DROP TABLE IF EXISTS programs CASCADE;
